### ISSUE TITLE
Create the app

### ISSUE THREAD

**Issue by C83** [C83/THP_2.0#1]
### Why ?
Creating the app, "the right way" will help the process as changing the default after is a bit tedious/difficult in rails.

### Must have:
- [x] Postgresql
- [x]   No front
- [x]   No Tests framework

### Todo
  - [x] Read through the rails new --help documentation
  - [x] Create the app

### Reading list
**What is rails api mode**
- [x] http://guides.rubyonrails.org/api_app.html

**What is a middleware**
- [x] http://railscasts.com/episodes/151-rack-
- [x] http://guides.rubyonrails.org/rails_on_rack.html#action-dispatcher-middleware-stack

**Comment by C83** [comment]
`rails new my_api --api -d postgresql -S -T -J -C --skip-turbolinks`

- ```--api``` disables few browser features, view part of the app and controllers inherit from ActionController:API instead of ActionController:Base.  
- ``` -d postgresql ``` to use postgresql instead of sqlite3
- ``` -C ``` to disable action-cable
- ``` -J ``` to disable javascript
- ``` -T ``` to disable test
- ``` -S ``` to disable sprocket (the gem provide asset pipeline but there is no view so no asset pipeline with api)
- ``` --skip-turbolinks ``` to disable turbolinks (the gem is used to improve and fluidify the navigation, useless with api)

**Comment by C83** [comment]
Done
