### ISSUE TITLE
Deployment pipeline in Heroku

### ISSUE THREAD

**Issue by C83** [C83/THP_2.0#8]
### Why ?
A fully automated deployment process will ensure that nobody ever push the wrong branch in deployment and will ensure that what is on Heroku is always up to date. It will also give us a staging env identical to production where we can test our feature one last time before updating the production (the only env clients see).

### Must have:
- [x]   Staging
- [x]   Prod
- [x]   Auto deploy master on Staging
- [x]   Deploy should run migrations

Each should have:
- [x]   Postgres

_Important:_ Do not configure your term to be able to talk to heroku.

### Todo

- [x]   Create an heroku pipeline
- [x]   Create the staging app
- [x]   Create the prod app
- [x]   Add postgres on both
- [x]   Add a [Procfile](https://devcenter.heroku.com/articles/getting-started-with-rails5#procfile) to the App
- [x]   Configure ruby version to 2.5.1 (.ruby-version) and add it to the Gemfile (ruby File.read('./.ruby-version'))
- [x]   Configure ruby gemset so you know your gems are for this app only (.ruby-gemset)
- [x]   Add a release step in your procfile to run the migrations (https://devcenter.heroku.com/articles/release-phase)
- [x]   Configure heroku so it auto deploys master on staging.
- [x]   Deploy it
- [x]   Promote to production
- [x]   Check that everything is right by running a console in Staging and creating a Lesson with it.

### Reading list

- https://www.heroku.com/dynos
- https://devcenter.heroku.com/articles/pipelines

**Comment by C83** [comment]
# .ruby-version and .ruby-gemset
Change the version of ruby in Gemfile. App will read the version in a file : `File.read('./.ruby-version')`
To create the .ruby-version and .ruby-gemset files : https://rvm.io/workflow/projects
`rvm --ruby-version use 2.5.1@course_api`
- course_api is the name of the gemset. It will create after. 
Then, leave and re-enter in the app repository : the new gemset will be used. So run `gem install bundler` and `bundle install` to install all gems in the new gemset. 

# Procfile : 
Create a new file called Procfile
Run puma server : `web: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}`
Add migration : `release: rails db:migrate`

**Comment by C83** [comment]
Master changed yesterday. Staging app updated automatically. Migrate done automatically with the Procfile. I create a new lesson on the app. I promoted on the production app.
